### PR TITLE
Add chromium plugin support

### PR DESCRIPTION
**Pull request by Sasytoremember**
Just added a couple lines of code and a plugin loader. I might need help with designing the plugin page, it's as far as i can go

### CODE REVIEW

**Comment by JaydenDev** [comment]
has this been tested... I have some doubts on if this will work

**Comment by JaydenDev** [comment]
@Sasytoremember, this doesn't work. I opened pluginLoader.html, selected a plugin and everything. Nothing happened! Probably because this ISN'T Chrome it just uses the CHROMIUM engine. Meaning Chrome plugins DO NOT work! This is CATALYST and plugins must be developed for CATALYST.

**Comment by Sasytoremember** [comment]
Don't close it just yet, there is some work to do, and you should fix it so it can work ( I don't know why it didn't check allow edits by maintainers )

**Comment by Sasytoremember** [comment]
And I did confirm that this works on electron.

**Comment by Sasytoremember** [comment]
Maybe it's something to do with the plugin loader html? I know for a fact the JS works.

**Comment by JaydenDev** [comment]
@Sasytoremember Catalyst can't just simply load Chrome extensions from a simple function, a compatibility layer must be built. You should wait until omnibar popups are supported (support for these will be added in v3.4)

**Comment by Sasytoremember** [comment]
> @Sasytoremember Catalyst can't just simply load Chrome extensions from a simple function, a compatibility layer must be built. You should wait until omnibar popups are supported (support for these will be added in v3.4)

Catalyst is based on Electron, which is based on Chromium. Chromium is 100% Compatible with normal chrome extensions, and  Electron contains the whole source tree of Chromium, and it would have a simple function to load extensions. But yes, we should work on this while omnibar popups get worked on.

**Comment by JaydenDev** [comment]
> > @Sasytoremember Catalyst can't just simply load Chrome extensions from a simple function, a compatibility layer must be built. You should wait until omnibar popups are supported (support for these will be added in v3.4)
> 
> Catalyst is based on Electron, which is based on Chromium. Chromium is 100% Compatible with normal chrome extensions, and Electron contains the whole source tree of Chromium, and it would have a simple function to load extensions. But yes, we should work on this while omnibar popups get worked on.

Catalyst isn't Chromium, do these look the same?
image

That's why all the functions will fail, that's why you don't see an SA icon on the Catalyst omnibar. There's no way a SA icon will just magically appear without any compatibility layers. The code at most could run, but nothing else will function.

**Comment by Sasytoremember** [comment]
> > > @Sasytoremember Catalyst can't just simply load Chrome extensions from a simple function, a compatibility layer must be built. You should wait until omnibar popups are supported (support for these will be added in v3.4)
> > 
> > 
> > Catalyst is based on Electron, which is based on Chromium. Chromium is 100% Compatible with normal chrome extensions, and Electron contains the whole source tree of Chromium, and it would have a simple function to load extensions. But yes, we should work on this while omnibar popups get worked on.
> 
> Catalyst isn't Chromium, do these look the same? image
> 
> That's why all the functions will fail, that's why you don't see an SA icon on the Catalyst omnibar. There's no way a SA icon will just magically appear without any compatibility layers. The code at most could run, but nothing else will function.
You are right, I was just saying they use the same codebase and at most only the code could run. And yes, we will need an omnibar compatibility layer. I'll look into how Chromium extensions work and implement a little compatibility layer.

**Comment by JaydenDev** [comment]
@Sasytoremember some of the omnibar work is already done, the search bar automatically shrinks when new elements are added to the utility bar.

**Comment by JaydenDev** [comment]
@Sasytoremember mark this PR as a draft

**Comment by JaydenDev** [comment]
@Sasytoremember anything new?

**Comment by jdev082** [comment]
@Sasytoremember any updates?

**Comment by michaeleldar** [comment]
> @Sasytoremember any updates?

I don't think this is going to get any more updates.

You should close it.

**Pull request closed without merging**
